"""Golden behavior tests for the audio conversion and analysis seam (P10).

WHY THESE EXIST: the P10 migration replaced the audio stack with soundfile +
a single FFmpeg subprocess call (owner decision D4, ADR 0006, roadmap P10
"golden behavior tests first"). These goldens were pinned FIRST, against the
pre-P10 implementation, and their assertion layer (values, tolerances,
semantics) must hold UNCHANGED against the replacement. Any drift beyond the
documented tolerances is a silent behavior change and must stop the migration.

LOCATION (tests/integration/, not tests/unit/): the goldens exercise real
filesystem I/O, real audio libraries, and — where FFmpeg is available — the
real ffmpeg binary. The unit suite marker explicitly excludes real
filesystem/system binaries, so integration is the natural home.

GOLDEN SET (roadmap P10): sample rate, frame counts, duration,
silence-threshold boundaries.

Method notes:
- Analysis goldens write PCM_16 WAVs with the stdlib ``wave`` module
  (stdlib-only generation: identical bytes in both regimes, so golden values
  cannot drift through the generator) and read the measured dBFS back out of
  the debug log, whose format is part of the pinned contract:
      "Audio analysis: {name} -> {dbfs:.1f} dBFS (threshold={t:.1f}, ...)"
- Theoretical dBFS of a full-band sine of amplitude A (rms = A/sqrt(2)):
      dBFS = 20 * log10(A / sqrt(2))
- Converter round-trip goldens require the ffmpeg binary and skip when it is
  absent (same availability-gating semantics as the rest of the integration
  suite).
"""

import math
import shutil
import struct
import wave
from collections.abc import Sequence
from pathlib import Path

import pytest
import soundfile as sf

from whisper_dictate.audio_analysis import is_audio_silent
from whisper_dictate.audio_converter import AudioConverter

SAMPLE_RATE = 16000
DURATION_S = 2.0
N_FRAMES = int(SAMPLE_RATE * DURATION_S)  # 32000

# Golden dBFS values (theoretical, verified empirically against the pre-P10
# stack in the phase-1 run; its dBFS was 20*log10(rms/32768), exactly the
# formula above for PCM_16 data normalized to ±1.0).
GOLDEN_DBFS_TONE = -9.03  # amplitude 0.5    -> not silent
GOLDEN_DBFS_QUIET = -63.01  # amplitude 0.001 -> silent
GOLDEN_DBFS_ABOVE = -49.76  # amplitude 0.0046 -> just ABOVE -50.0 -> NOT silent
GOLDEN_DBFS_BELOW = -50.97  # amplitude 0.0040 -> just BELOW -50.0 -> silent
GOLDEN_DBFS_STEREO_HALF = -12.04  # L: A=0.5 tone, R: silence (rms over all samples)
DBFS_TOLERANCE = 0.15  # 16-bit quantization noise is <0.01 dB; the replaced
# stack's audioop.rms integer rounding added up to ~0.1 dB at the quietest
# golden (-63.1 vs the exact -63.000328), all inside this tolerance

# Converter round-trip tolerances (recorded from the phase-1 pre-P10 run).
FRAME_COUNT_TOLERANCE = 2000  # MP3 encoder delay/padding only; sample-rate
# mangling would blow far past this
DURATION_TOLERANCE_S = 0.125  # matches FRAME_COUNT_TOLERANCE at 16 kHz


def _write_pcm16_wav(path: Path, amplitudes: Sequence[float], freq: float = 440.0) -> Path:
    """Write a sine WAV (16-bit PCM) via the stdlib ``wave`` module.

    One amplitude per channel (interleaved). Stdlib-only on purpose: the
    generated bytes are identical across the pre- and post-P10 regimes.
    """
    channels = len(amplitudes)
    frames = bytearray()
    for i in range(N_FRAMES):
        for amplitude in amplitudes:
            value = round(amplitude * 32767 * math.sin(2 * math.pi * freq * i / SAMPLE_RATE))
            frames += struct.pack("<h", value)
    with wave.open(str(path), "wb") as wf:
        wf.setnchannels(channels)
        wf.setsampwidth(2)
        wf.setframerate(SAMPLE_RATE)
        wf.writeframes(bytes(frames))
    return path


def _make_wav(tmp_path: Path, name: str, amplitude: float, channels: int = 1) -> Path:
    return _write_pcm16_wav(tmp_path / name, [amplitude] * channels)


# ============ Analysis goldens (no ffmpeg needed) ============


class TestGoldenSilenceAnalysis:
    """Golden values for is_audio_silent: dBFS math, threshold boundary,
    stereo handling, fail-open."""

    @staticmethod
    def _dbfs_from_log(caplog: pytest.LogCaptureFixture, filename: str) -> float:
        """Parse the measured dBFS out of the pinned debug-log format."""
        for record in caplog.records:
            message = record.getMessage()
            if "Audio analysis:" in message and filename in message:
                raw = message.split("-> ")[1].split(" dBFS")[0]
                return float(raw)  # float("-inf") parses naturally
        raise AssertionError(f"No 'Audio analysis' debug log found for {filename}")

    def _measure(self, caplog: pytest.LogCaptureFixture, wav: Path) -> tuple[bool, float]:
        with caplog.at_level("DEBUG"):
            verdict = is_audio_silent(wav)
        return verdict, self._dbfs_from_log(caplog, wav.name)

    def test_tone_above_threshold(self, tmp_path, caplog):
        """A 0.5-amplitude 440 Hz sine measures ~-9.03 dBFS -> not silent."""
        wav = _make_wav(tmp_path, "golden_tone.wav", 0.5)
        verdict, dbfs = self._measure(caplog, wav)
        assert verdict is False
        assert dbfs == pytest.approx(GOLDEN_DBFS_TONE, abs=DBFS_TOLERANCE)

    def test_quiet_audio_is_silent(self, tmp_path, caplog):
        """A 0.001-amplitude sine measures ~-63.01 dBFS -> silent."""
        wav = _make_wav(tmp_path, "golden_quiet.wav", 0.001)
        verdict, dbfs = self._measure(caplog, wav)
        assert verdict is True
        assert dbfs == pytest.approx(GOLDEN_DBFS_QUIET, abs=DBFS_TOLERANCE)

    def test_digital_silence_is_negative_inf(self, tmp_path, caplog):
        """All-zero audio measures -inf dBFS -> silent (strict < holds)."""
        wav = _make_wav(tmp_path, "golden_silence.wav", 0.0)
        verdict, dbfs = self._measure(caplog, wav)
        assert verdict is True
        assert dbfs == float("-inf")

    def test_boundary_just_above_threshold_not_silent(self, tmp_path, caplog):
        """-49.76 dBFS is above the -50.0 threshold -> NOT silent."""
        wav = _make_wav(tmp_path, "golden_above.wav", 0.0046)
        verdict, dbfs = self._measure(caplog, wav)
        assert verdict is False
        assert dbfs == pytest.approx(GOLDEN_DBFS_ABOVE, abs=DBFS_TOLERANCE)
        assert dbfs > -50.0

    def test_boundary_just_below_threshold_silent(self, tmp_path, caplog):
        """-50.97 dBFS is below the -50.0 threshold -> silent."""
        wav = _make_wav(tmp_path, "golden_below.wav", 0.0040)
        verdict, dbfs = self._measure(caplog, wav)
        assert verdict is True
        assert dbfs == pytest.approx(GOLDEN_DBFS_BELOW, abs=DBFS_TOLERANCE)
        assert dbfs < -50.0

    def test_stereo_rms_spans_all_samples(self, tmp_path, caplog):
        """Asymmetric stereo (L: 0.5 tone, R: silence) measures ~-12.04 dBFS.

        Pins the rms-over-all-samples semantics: the pre-P10 dBFS ran
        audioop.rms over the interleaved byte stream (all channels), and the
        replacement must flatten channels identically. (A per-channel or
        first-channel rms would read -9.03 instead of -12.04 — measured
        -12.042260 on the pre-P10 stack.)
        """
        wav = _write_pcm16_wav(tmp_path / "golden_stereo.wav", [0.5, 0.0])
        verdict, dbfs = self._measure(caplog, wav)
        assert verdict is False
        assert dbfs == pytest.approx(GOLDEN_DBFS_STEREO_HALF, abs=DBFS_TOLERANCE)

    def test_default_threshold_is_minus_fifty(self, tmp_path, caplog):
        """Default threshold_dbfs=-50.0: the quiet file is silent by default."""
        wav = _make_wav(tmp_path, "golden_default.wav", 0.001)
        with caplog.at_level("DEBUG"):
            verdict = is_audio_silent(wav)
        assert verdict is True
        assert "threshold=-50.0" in self._raw_log(caplog, wav.name)

    def test_fail_open_on_missing_file(self, tmp_path, caplog):
        """Unreadable file -> fail-open False (any error; message may name the
        underlying cause, which legitimately differs per implementation)."""
        missing = tmp_path / "does_not_exist.wav"
        with caplog.at_level("WARNING"):
            verdict = is_audio_silent(missing)
        assert verdict is False
        assert any("Failed to analyze audio" in r.getMessage() for r in caplog.records)

    @staticmethod
    def _raw_log(caplog: pytest.LogCaptureFixture, filename: str) -> str:
        for record in caplog.records:
            message = record.getMessage()
            if "Audio analysis:" in message and filename in message:
                return message
        raise AssertionError(f"No 'Audio analysis' debug log found for {filename}")


# ============ Converter round-trip goldens (ffmpeg required) ============


def _ffmpeg_available() -> bool:
    return shutil.which("ffmpeg") is not None


class TestGoldenConverterRoundTrip:
    """Real WAV -> MP3 round-trips through the public convert() contract.

    Skipped where the ffmpeg binary is unavailable (unit seam tests cover the
    fallback contract there).
    """

    @pytest.fixture(autouse=True)
    def require_ffmpeg(self):
        if not _ffmpeg_available():
            pytest.skip("FFmpeg not available - real round-trip goldens need the ffmpeg binary")

    @staticmethod
    def _make_source(tmp_path: Path, name: str = "golden_source.wav") -> Path:
        return _make_wav(tmp_path, name, 0.5)

    def test_roundtrip_preserves_sample_rate_and_duration(self, tmp_path):
        """2 s / 16 kHz sine survives the round-trip: 16000 Hz exactly,
        frame count within encoder-delay tolerance of 32000."""
        wav = self._make_source(tmp_path)
        mp3 = AudioConverter(bitrate="128k", keep_wav=True).convert(wav)

        assert mp3 == wav.with_suffix(".mp3")
        assert mp3.exists()

        data, rate = sf.read(mp3, dtype="float32")
        assert rate == SAMPLE_RATE  # sample rate is preserved exactly
        assert abs(len(data) - N_FRAMES) <= FRAME_COUNT_TOLERANCE
        duration = len(data) / rate
        assert duration == pytest.approx(DURATION_S, abs=DURATION_TOLERANCE_S)

    def test_roundtrip_64k_materially_smaller_than_128k(self, tmp_path):
        """64k output is materially smaller than 128k output (>25% smaller)."""
        # Two distinct sources: convert() always writes to <source>.mp3, so a
        # single source would overwrite the 128k output with the 64k one.
        wav_128 = self._make_source(tmp_path, "golden_128_source.wav")
        wav_64 = self._make_source(tmp_path, "golden_64_source.wav")
        mp3_128 = AudioConverter(bitrate="128k", keep_wav=True).convert(wav_128)
        mp3_64 = AudioConverter(bitrate="64k", keep_wav=True).convert(wav_64)

        size_128 = mp3_128.stat().st_size
        size_64 = mp3_64.stat().st_size
        assert size_64 < 0.75 * size_128, f"64k MP3 ({size_64} B) should be materially smaller than 128k ({size_128} B)"

    def test_roundtrip_achieves_real_compression(self, tmp_path):
        """128k MP3 of the 2 s source is < 75% of the WAV size."""
        wav = self._make_source(tmp_path)
        wav_size = wav.stat().st_size
        mp3 = AudioConverter(bitrate="128k", keep_wav=True).convert(wav)
        assert mp3.stat().st_size < 0.75 * wav_size

    def test_deletion_semantics_default_deletes_source(self, tmp_path):
        """keep_wav=False (default): source WAV deleted on success only."""
        wav = self._make_source(tmp_path)
        mp3 = AudioConverter(bitrate="128k").convert(wav)
        assert not wav.exists()
        assert mp3 == wav.with_suffix(".mp3")
        assert mp3.exists()

    def test_deletion_semantics_delete_source_false_keeps_source(self, tmp_path):
        """delete_source=False preserves the WAV even with keep_wav=False."""
        wav = self._make_source(tmp_path)
        mp3 = AudioConverter(bitrate="128k").convert(wav, delete_source=False)
        assert wav.exists()
        assert mp3 == wav.with_suffix(".mp3")
        assert mp3.exists()

    def test_deletion_semantics_delete_source_true_overrides_keep_wav(self, tmp_path):
        """delete_source=True overrides keep_wav=True."""
        wav = self._make_source(tmp_path)
        mp3 = AudioConverter(bitrate="128k", keep_wav=True).convert(wav, delete_source=True)
        assert not wav.exists()
        assert mp3 == wav.with_suffix(".mp3")
        assert mp3.exists()

    def test_missing_input_returns_wav_never_raises(self, tmp_path, caplog):
        """Missing input file: never raises, returns the original WAV path,
        and logs a warning. (The warning's embedded cause text legitimately
        differs per implementation; the never-raises + return-WAV contract
        is the pinned part.)"""
        wav = tmp_path / "missing.wav"
        with caplog.at_level("WARNING"):
            result = AudioConverter().convert(wav)
        assert result == wav
        assert any(r.levelno >= 30 for r in caplog.records)


# ============ Implementation seams ============
# NO phase-specific fixture is needed anymore: since the P10 swap
# (soundfile + FFmpeg subprocess, ADR 0006) the modules under test bind real
# soundfile at collection time (module-level import, dictation.py precedent)
# and invoke the real ffmpeg binary. The phase-1-only real-stack sys.modules
# swap fixture was deleted along with the outgoing dependency.
